# Treinando uma rede neural com pytorch

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim

In [2]:
class MLP(nn.Module):
    def __init__(self, num_dados_entrada, neuronios_c1, neuronios_c2, num_targets):
        super().__init__()
        
        self.camadas = nn.Sequential(
            nn.Linear(num_dados_entrada, neuronios_c1),
            nn.Sigmoid(),
            nn.Linear(neuronios_c1, neuronios_c2),
            nn.Sigmoid(),
            nn.Linear(neuronios_c2, num_targets),
        )
        
    def forward(self, x):
        x = self.camadas(x)
        return x

In [3]:
x = [
  [2.0, 3.0, -1.0],
  [3.0, -1.0, 0.5],
  [0.5, 1.0, 1.0],
  [1.0, 1.0, -1.0],
]

y_true = [1, 0, 0.2, 0.5]

In [4]:
x = torch.tensor(x)

In [5]:
x

tensor([[ 2.0000,  3.0000, -1.0000],
        [ 3.0000, -1.0000,  0.5000],
        [ 0.5000,  1.0000,  1.0000],
        [ 1.0000,  1.0000, -1.0000]])

In [6]:
y_true = torch.tensor(y_true)

In [7]:
y_true

tensor([1.0000, 0.0000, 0.2000, 0.5000])

In [8]:
y_true = y_true.view(-1, 1)

In [9]:
y_true

tensor([[1.0000],
        [0.0000],
        [0.2000],
        [0.5000]])

In [10]:
NUM_DADOS_DE_ENTRADA = 3  
NUM_DADOS_DE_SAIDA = 1  
NEURONIOS_C1 = 3
NEURONIOS_C2 = 2

minha_mlp = MLP(
    NUM_DADOS_DE_ENTRADA, NEURONIOS_C1, NEURONIOS_C2, NUM_DADOS_DE_SAIDA
)

In [11]:
for p in minha_mlp.parameters():
    print(p)

Parameter containing:
tensor([[-0.3226, -0.2712, -0.5433],
        [-0.5189, -0.2707,  0.2483],
        [-0.4040,  0.5463, -0.1080]], requires_grad=True)
Parameter containing:
tensor([-0.3580,  0.1269,  0.0575], requires_grad=True)
Parameter containing:
tensor([[-0.3771, -0.2682,  0.4061],
        [-0.5264,  0.1532, -0.0636]], requires_grad=True)
Parameter containing:
tensor([-0.5007,  0.4522], requires_grad=True)
Parameter containing:
tensor([[-0.5479,  0.0019]], requires_grad=True)
Parameter containing:
tensor([-0.2973], requires_grad=True)


In [12]:
y_prev = minha_mlp(x)
y_prev

tensor([[-0.5267],
        [-0.4915],
        [-0.5068],
        [-0.5038]], grad_fn=<AddmmBackward0>)

In [14]:
TAXA_DE_APRENDIZADO = 0.001

otimizador = optim.SGD(minha_mlp.parameters(), lr=TAXA_DE_APRENDIZADO)

In [15]:
fn_perda = nn.MSELoss()

In [16]:
NUM_EPOCAS = 100

minha_mlp.train()

for epoca in range(NUM_EPOCAS):
    # forward pass
    y_pred = minha_mlp(x)

    # zero grad
    otimizador.zero_grad()

    # loss
    loss = fn_perda(y_true, y_pred)

    # backpropagation
    loss.backward()

    # atualiza parâmetros
    otimizador.step()

    # mostra resultado (opcional)
    print(epoca, loss.data)

0 tensor(1.0199)
1 tensor(1.0147)
2 tensor(1.0094)
3 tensor(1.0043)
4 tensor(0.9991)
5 tensor(0.9940)
6 tensor(0.9889)
7 tensor(0.9838)
8 tensor(0.9787)
9 tensor(0.9737)
10 tensor(0.9688)
11 tensor(0.9638)
12 tensor(0.9589)
13 tensor(0.9540)
14 tensor(0.9491)
15 tensor(0.9443)
16 tensor(0.9395)
17 tensor(0.9347)
18 tensor(0.9300)
19 tensor(0.9253)
20 tensor(0.9206)
21 tensor(0.9160)
22 tensor(0.9113)
23 tensor(0.9067)
24 tensor(0.9022)
25 tensor(0.8976)
26 tensor(0.8931)
27 tensor(0.8886)
28 tensor(0.8842)
29 tensor(0.8797)
30 tensor(0.8753)
31 tensor(0.8710)
32 tensor(0.8666)
33 tensor(0.8623)
34 tensor(0.8580)
35 tensor(0.8537)
36 tensor(0.8495)
37 tensor(0.8453)
38 tensor(0.8411)
39 tensor(0.8369)
40 tensor(0.8327)
41 tensor(0.8286)
42 tensor(0.8245)
43 tensor(0.8205)
44 tensor(0.8164)
45 tensor(0.8124)
46 tensor(0.8084)
47 tensor(0.8044)
48 tensor(0.8005)
49 tensor(0.7966)
50 tensor(0.7927)
51 tensor(0.7888)
52 tensor(0.7850)
53 tensor(0.7811)
54 tensor(0.7773)
55 tensor(0.7735)
56

In [17]:
x_teste = [
  [2.5, 3.1, -0.4],
  [2.0, -1.5, 1.0],
]

y_teste = [0.8, 0.2]

x_teste = torch.tensor(x_teste)
y_teste = torch.tensor(y_teste)
y_teste = y_teste.view(-1,1)

In [18]:
minha_mlp.eval()

MLP(
  (camadas): Sequential(
    (0): Linear(in_features=3, out_features=3, bias=True)
    (1): Sigmoid()
    (2): Linear(in_features=3, out_features=2, bias=True)
    (3): Sigmoid()
    (4): Linear(in_features=2, out_features=1, bias=True)
  )
)

In [19]:
with torch.no_grad():
    y_pred = minha_mlp(x_teste)

In [20]:
y_pred

tensor([[-0.2824],
        [-0.2437]])

In [22]:
from sklearn.metrics import mean_squared_error

RMSE = mean_squared_error(y_teste, y_pred, squared=False)
print(RMSE)

0.8271519
